scss:
  enabled: false

stylelint:
  enabled: true

rubocop:
  config_file: .rubocop.yml
  version: 0.80.0

jshint:
  enabled: false

eslint:
  enabled: false
  config_file: .eslintrc
  ignore_file: .eslintignore

fail_on_violations: true
