require:
  - rubocop-performance
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'config/routes.rb'
    - 'node_modules/**'
    - 'test/**/*'
    - 'doc/plugins/**'

Rails:
  Enabled: true
  Exclude:
    - 'lib/foreman_remote_execution_core/**'
    - 'node_modules/**'

Rails/Date:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

#Style/TrailingCommaInArguments:
#Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Naming/FileName:
  Exclude:
      - 'db/seeds.d/*'
      - 'node_modules/font-awesome-sass/lib/font-awesome-sass.rb'

Style/WordArray:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# a == 0 is not the same as a.zero?, when a is not a number
Style/NumericPredicate:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Rails/SkipsModelValidations:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
