inherit_gem:
  theforeman-rubocop:
    - lenient.yml
    - minitest.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.2
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Metrics:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Rails:
  Exclude:
    - 'lib/foreman_remote_execution_core/**/*'
    - 'lib/foreman_remote_execution_core.rb'

Rails/Blank:
  UnlessPresent: false

# Won't work with sqlite
Rails/BulkChangeTable:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce certain methods, e.g. detect over find
Style/CollectionMethods:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Support both, Ruby 1.9 hashmap and hash-rocket syntax
Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
