inherit_from:
  - .rubocop_todo.yml

AllCops:
  RunRailsCops: true # always run the rails cops

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

Metrics/MethodLength:
  Max: 40

Style/TrailingComma:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Rails/FindBy:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Style/WordArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
