inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'doc/plugins/**'

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Style/TrailingCommaInLiteral:
  Enabled: false

#Style/TrailingCommaInArguments:
#Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/ClassLength:
  Max: 500
  Exclude:
       - 'test/**/*'

Style/FileName:
  Exclude:
      - 'db/seeds.d/*'

Style/WordArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
       - 'config/routes.rb'
       - 'lib/foreman_remote_execution/engine.rb'
       - 'test/**/*'

Metrics/ParameterLists:
  Enabled: false

Style/VariableNumber:
  Enabled: false

# a == 0 is not the same as a.zero?, when a is not a number
Style/NumericPredicate:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Rails/SkipsModelValidations:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# for compatibility with Foreman 1.15
Rails/ApplicationRecord:
  Enabled: false

Style/FormatString:
  Enabled: false
